- name: Copying {{COMPONENT}}
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install {{COMPONENT}} on remote servers
  ansible.builtin.package:
    name: mongodb-org
    state: present    

- name: Enabling {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting {{COMPONENT}}
  ansible.builtin.service:
    state: started
    name: mongod
    enabled: yes
    daemon_reload: yes
   
- name: Download and extract {{COMPONENT}} schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Injecting schema
  ansible.builtin.shell: mongo --host mongodb-dev.roboshop.internal < /tmp/mongodb-main/{{item}}.js
  loop: 
    - catalogue
    - users

- name: Changing {{COMPONENT}} hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}

    