- name: Demo on shell module
  hosts: all

  tasks:
  - name: Task 1 for shell module
    ansible.builtin.shell: uptime
    register: OUT

  - name: Task 2 to print o/p of shell module
    debug:
      msg: Uptime of server is {{OUT.stdout}}

  - name: Task 2 to capture bash exit code
    ansible.builtin.set_fact:
      EXITCODE: "{{OUT.rc}}" 

  - name: Task 3 to print bash exit code 
    debug:
      msg: Exitcode of server is {{EXITCODE}}

# ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 04-shell.yaml