- name: Demo on Package
  hosts: all
  become: yes

  tasks:
    - name: Installing a package
      ansible.builtin.package: 
        name: nginx
        state: present

    - name: Checking a package
      ansible.builtin.shell: type nginx
      register: OUT

    - name: Printing a package
      ansible.builtin.debug:
        msg: "{{OUT.stdout}} installed"

    - name: Install latest version of wget and jq
      ansible.builtin.package: 
        name:
          - wget
          - jq
        state: latest                                           # latest checks installs latest pck