-   name: play1
    hosts: all
    tasks:
      - name: task 1
        ansible.builtin.debug:
          msg: This msg is from debug module Task1


      - name: task 2
        ansible.builtin.debug:
          msg: This msg is from debug module Task 2

-   name: play2
    hosts: all
    tasks:
      - name: task 1 of play2
        ansible.builtin.debug:
          msg: Hii from debug module Task1


      - name: task 2 of play2
        ansible.builtin.debug:
          msg: Hello from debug module Task 2