- name: Variable demo
  hosts: all
  vars:
    name: Saurabh
  tasks:
    - name: task1
      debug:
        msg: this is the 1st task msg

    - name: task2
      debug:
        msg: "Name of person runing the script is {{name}}"      

    - name: task3
      debug:
        msg: "Name of person runing the script is {{name}}"   
      vars:
        name: SD

    - name: task4
      debug:
        msg: "Name of person who runing the script is {{name}} and he is from {{city}} city"   
         