- name: Demo on shell module
  hosts: all

  tasks:
  - name: Task 2 for shell module
    ansible.builtin.shell: uptime
    register: OUT

  - name: Task 3 to print o/p of shell module
    debug:
      msg: Uptime of server is {{OUT.stdout}}

  - name: Task 3 to capture bash exit code
    ansible.builtin.sset_facts:
      EXITCODE: "{{OUT.rc}}" 