- name: Demo on Escalations
  hosts: all

  tasks:
    - name: Checking user
      ansible.builtin.shell:
      register: OUT

    - name: Printing users
      ansible.builtin.debug:
        msg: User name is {{OUT.stdout}}   
      