- name: Demo on Escalations
  hosts: all

  tasks:
    - name: Checking user
      ansible.builtin.shell: id
      register: OUT

    - name: Printing users
      ansible.builtin.debug:
        msg: User name is {{OUT.stdout}}   

    - name: Crating roboshop user
      ansible.builtin.user:
        name: robot     
      