- name: Demo on Escalations
  hosts: all
  become: true

  tasks:
    - name: Checking user
      ansible.builtin.shell: id
      register: OUT
      become_user: centos                      # become user to run perticular task as a user

    - name: Printing users
      ansible.builtin.debug:
        msg: User name is {{OUT.stdout}} 

    - name: Crating roboshop user
      ansible.builtin.user:
        name: robot 

    - name: Checking user robot
      ansible.builtin.shell: id robot
      register: OUT

    - name: Printing robot user id
      ansible.builtin.debug:
        msg: Robot User ID is {{OUT.stdout}}              
      
# ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 08-provEscalation.yaml