#Copying rsyslog file
- name: Copying the RSYSLOG file
  ansible.builtin.template:
    src: syslog.conf
    dest: /etc/rsyslog.d/rsyslog.conf

- name: Restarting rsyslog
  ansible.builtin.service:
    state: restarted
    name: rsyslog
    daemon_reload: true