- name: Disable Default repo and configure {{COMPONENT}} 5.7 repo
  ansible.builtin.shell: dnf module disable mysql -y 

- name: Copying {{COMPONENT}}
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install {{COMPONENT}}
  ansible.builtin.package:
    name: mysql-community-server -y
    state: present 

- name: Starting {{COMPONENT}}
  ansible.builtin.service:
    state: started
    name: mysqld
    enabled: yes
   # daemon_reload: yes






