- name: Disabling default nodejs version
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

- name: Install nodejs on remote servers
  ansible.builtin.package:
    name: nodejs
    state: installed