- name: Copying the prometheus conf file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restarting logstash
  ansible.builtin.service:
    state: restarted
    name: prometheus
    enabled: true
    daemon_reload: true

- name: Wait for port 9090 port up
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 20