- name: Copying systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/systemd.service

- name: Restarting {{COMPONENT}}
  ansible.builtin.service:
    state: restarted
    name: "{{COMPONENT}}"
    enabled: yes
    daemon_reload: true
