- name: Performing {{COMPONENT}} cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent
  ignore_errors: true

- name: Creating {{COMPONENT}} App Directory
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: directory
    mode: '0755'
  become_user: "{{APPUSER}}"

- name: Download and extract {{COMPONENT}} from Nexus
  ansible.builtin.unarchive:
    src: http://172.31.4.200:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/{{APPUSER}}/{{COMPONENT}}/ 
    remote_src: yes
  become_user: "{{APPUSER}}"