- name: Download and extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: http://172.31.4.200:8081/repository/${COMPONENT}/${COMPONENT}-${APP_VERSION}.zip
    dest: /tmp
    remote_src: yes

- name: Performing {{COMPONENT}} cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent

- name: Copying {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes