- name: Disabling default nodejs version and installing nodejs:18
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

- name: Install nodejs on remote servers
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating {{APPUSER}} user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and extract {{COMPONENT}}
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /home/{{APPUSER}}/global-bundle.pem
  become_user: "{{APPUSER}}"

- name: Dealing Artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download_extracts

- name: Generating Artifacts
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Configuring service for {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: configure_service

- name: Set Host-name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname