- name: Disabling default nodejs version and installing nodejs:18
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

- name: Install nodejs on remote servers
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating {{APPUSER}} user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download pem key 
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /home/{{APPUSER}}/global-bundle.pem
  become_user: "{{APPUSER}}"

## Uncomment this if you want to use the artifacts from Github
# - name: Dealing Artifacts
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_extracts

# - name: Generating Artifacts
#   community.general.npm:
#     path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Downloading Artifacts From Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_extracts_nexus

- name: Configuring service for {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: configure_service

- name: Installing filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

- name: Set Host-name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname