- name: Install python on remote servers
  ansible.builtin.package:
    name: 
      - python36 
      - gcc 
      - python3-devel
    state: present

- name: Creating {{APPUSER}} user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user
    
# Uncomment this if you want to use the artifacts from Github
# - name: Dealing Artifacts
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_extracts

- name: Downloading Artifacts From Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_extracts_nexus

- name: Generating Artifacts
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3.6
    
- name: Configuring service for {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: configure_service

- name: Configuring rsyslog
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog

- name: Installing filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

- name: Installing prometheus
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node_exporter
    
- name: Set Host-name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname